name = "gw2tool"
main = "src/index.js"
compatibility_date = "2025-05-01"

# Workers KV 命名空间绑定
[[kv_namespaces]]
binding = "GW2_DATA"
id = "33d17db1ec9a4054be429822a89500a8"

# Workers Assets - 自动托管静态文件
[assets]
directory = "./"
html_handling = "auto-trailing-slash"
not_found_handling = "single-page-application"
